version: '0.2.0+{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

branches:
  only:
    - master
    - development

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build && cd build && cmake ..

build_script:
  - cmake --build .

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build && %CONFIGURATION%\tests.exe