dist: trusty

language: c
os: linux

compiler:
  - gcc

branches:
  only:
    - master
    - development

addons: 
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7

before_script:
  - export CC=gcc-7
  - mkdir build/ && cd build/ && cmake ..

script:
  - cmake --build . && ./tests