dist: trusty

language: c
os: linux

compiler:
  - gcc
  - clang 

branches:
  only:
    - master
    - development

before_script:
  - mkdir build/ && cd build/ && cmake ..

script:
  - cmake --build . && ./tests